version : '3'

services:
    vue:
      container_name: vue
      build: ./
      working_dir: /home/vue-quasar-company-profile-website
      ports:
      - 8000:8000
      command: quasar dev --port 8000
      
